# Generated by Django 5.2.12 on 2026-05-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("target", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("content", models.TextField()),
            ],
        ),
    ]
