# Generated by Django 5.2.12 on 2026-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_clone", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="fingerprint",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
