# Generated by Django 5.2.12 on 2026-06-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_clone", "0002_message_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="fingerprint",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, null=True, unique=True
            ),
        ),
    ]
